### ISSUE TITLE
Conversation not extracted

### ISSUE THREAD

**Issue by ciceline** [Mincka/DMArchiver#18] opened 2017-06-25 13:37 UTC
Hello,
I tried to extract a twitter DM conversation with the macOS version, but I encountered two issues:
1. the screen says "Process completed", I can find the .txt files in Finder but the conversation I need has not been extracted (I maybe have two dozens conversations, but I only need that one)
2. the extracted conversations look like this: no DM visible. Did I do something wrong?
![screen shot 2017-06-25 at 15 35 46](https://user-images.githubusercontent.com/29689797/27516524-fe6dba62-59bb-11e7-98db-e6646fad41b8.png)

My boyfriend died in April. I'm trying to save our twitter DMs... Thanks for any help.
Celine

**Comment by sussron** [comment] 2017-06-25 20:49
This is exactly what happened to me yesterday when i tried to do the same
thing Julien. I posted on the board and sent an email to you.
Celine i' very sorry you lost your boyfriend in April, my condolences,

Ronnie

**Comment by Mincka** [comment] 2017-06-26 06:20
Hello Celine & Ronnie,

I'm sorry for your loss Celine.

It seems you both have the same issue. I tested again yesterday with the macOS version but did not get this issue. Do you know what version of macOS do you have? Do you have the same issue for all the conversations?

Celine, regarding the missing conversations, this is related to another bug ( #8) that I will fix soon.

It's quite hard for me to test the macOS version because I do not own a mac. I will investigate tonight. Thank you for the issue reporting.

**Comment by Mincka** [comment] 2017-06-26 21:28
I've updated my system to macOS Sierra 10.12.5, but I still do not manage to reproduce the bug. Still, I've rebuilt a version that you can test but I guess the issue will still be the same...

-> Edit: Please check latest release (https://github.com/Mincka/DMArchiver/releases/tag/0.1.4) instead.

[dmarchiver-macos-testbuild-2017-06-26.zip](https://github.com/Mincka/DMArchiver/files/1103523/dmarchiver-macos-testbuild-2017-06-26.zip)

**Comment by Mincka** [comment] 2017-06-26 21:58
I managed to build a version with another Python version (3.4.4) which is older but may work better. Emojis in the nicknames should be displayed correctly for example.

-> Edit: Please check latest release (https://github.com/Mincka/DMArchiver/releases/tag/0.1.4) instead.

[dmarchiver-macos-testbuild-2017-06-26-python344.zip](https://github.com/Mincka/DMArchiver/files/1103604/dmarchiver-macos-testbuild-2017-06-26-python344.zip)

Maybe you will not have the bug with this version. Please test both and tell me if one of them works better for you.

Thanks a lot.

**Comment by ciceline** [comment] 2017-06-26 22:12
Dear Julien,

thanks a lot for you efforts... I will try again tomorrow and let you know.

all the best,
Celine

**Comment by sussron** [comment] 2017-06-28 02:32
i have 10.12.5 Julien
I'm going to try to download what you sent tomorrow as i've worked late
tonight.
thanks for your quick response.
Ronnie

**Comment by sussron** [comment] 2017-06-28 02:41
Julien
i am testing the first one now and it's working. I may have inadvertantly
caused the problem. I moved all the old versions of dmarchiver and
resulting files into another folder from Downloads and ran this new version
fresh and so far i'm not getting the error. I will let you know tomorrow
when the resulting file comes up and see if the messages are included
besides just the names and dates.  Thanks!!!  Ronnie

**Comment by Mincka** [comment] 2017-06-28 07:03
Ronnie, Celine,

I've released version 0.1.4 which should fix this bug and #8 (Not all conversations downloaded).
https://github.com/Mincka/DMArchiver/releases/tag/0.1.4

Thank you for your feedback.

Julien

**Comment by sussron** [comment] 2017-06-28 12:28
it worked it worked it worked!!  Hooray and thanks!!!

**Comment by ciceline** [comment] 2017-06-28 12:31
Thanks Julien, and Roonie for confirming it works.

I didn't have time to test yesterday night but will definitely get around
it today.

Celine

**Comment by Mincka** [comment] 2017-06-28 13:07
Thanks Ronnie. 😄 The next thing I will add will be the incremental updates to make subsequent backups really quick. It's nice to have you to test the tool!

Celine, please use the latest version available:
https://github.com/Mincka/DMArchiver/releases/tag/0.1.4

I close this ticket but do not hesitate to post here for feedback or create another issue. Thanks.

**Closed as completed by Mincka** 2017-06-28 13:07 UTC

**Comment by ciceline** [comment] 2017-06-28 20:10
Thanks a million Julien. It works perfectly on macOS Sierra 10.12.5.
Thanks to both for the kind words too.

All the best, Celine

**Comment by Mincka** [comment] 2017-06-28 22:25
Thanks for the feedback Celine. Hope it will help you. #JusticeForYaamyn

**Comment by ciceline** [comment] 2017-06-28 23:10
Hopefully... maybe 💔

**Comment by wedad-s** [comment] 2018-10-20 04:02
it not work :(
when i put my name and password i didn't found any thing
